### ISSUE TITLE
db disconnected error

### ISSUE THREAD

**Issue by wencaizhong** [dipetkov/actigraph.sleepr#2]
hi, when executing the function read_agd it occurs: Error in rsqlite_send_query(conn@ptr, statement) : disconnected
I checked the code and found that line 126 `DBI::dbDisconnect(db)` executes before line 134 
`if ("capsense" %in% tables_agd)
    tables$capsense <- select_dttms("capsense", "timeStamp")`, which seems unreasonable.
My agd files do have capsense table.

**Comment by dipetkov** [comment]
Yes, you are correct. Thank you for pointing out the bug; I have fixed it.
