### ISSUE TITLE
Sleep state conditions

### ISSUE THREAD

**Issue by barnzilla** [dipetkov/actigraph.sleepr#3]
First of all, great code! Thanks for making this available.

Just wanted to mention something very minor: in a comment on line 26 of apply_sadeh.R, it's stated that "the sleep state is awake (W) if the sleep index SI is greater than -4; otherwise the sleep state is asleep (S)." I think it's the opposite though, based on your code on line 71: if_else(.data$sleep > -4, "S", "W")

**Comment by dipetkov** [comment]
You are quite right. Thank you for letting me know, I've fixed the documentation. (I've checked the paper and the equation is implemented correctly, but documented wrongly.)

**Comment by barnzilla** [comment]
No worries at all. Again, thanks for making the code available!
