### ISSUE TITLE
Why did you choose to skip a zero in Sadeh algorithm Formula ?

### ISSUE THREAD

**Issue by simonprovost** [dipetkov/actigraph.sleepr#4]
**Hello Dipetkov,**

First and foremost, thank you for this library which is really helpful. After few inspecting of your source I have seen something which stopped me and where asked myself about something.

Regarding to this article https://onlinelibrary.wiley.com/doi/full/10.1111/j.1365-2869.2008.00706.x we could see that they said that the formula for sadeh algorithm is something like this : 

https://onlinelibrary.wiley.com/cms/asset/4675b32c-07d7-4618-8a77-cd904f947b17/jsr_706_m7.gif (Click on this link to see the formula in jpeg.)

We can see that in the 4th pattern they said to use this constant :  0.0703.
And in your source we could see this constant :  0.703. 

Was it your choice ? if it is, why did you do that ? I am curious to know more about this. I am not yet an expert in that domain but I am currently learning and trying something.

We can say that we have better result with 0.703 indeed than with 0.0703.

Thank you for your listening,
Sincerely.

**Comment by simonprovost** [comment]
@dipetkov I am confused, regarding to that link : https://www.researchgate.net/publication/15260355_Activity-Based_Sleep-Wake_Identification_An_Empirical_Test_of_Methodological_Issues We can see that they use 0.703 constant instead of 0.0703 like I have seen.

Could you tell me what the side effects might be?

**Comment by dipetkov** [comment]
Hello

This is the equation in the original paper:
```
PS = 7.601 - 0.065 · Mean-W-5-min - 1.08 · NAT - 0.056 · SD-last 6 min - 0.703·LOG-Act
```
This is the equation exactly as it appears on page 202 in Sleep, Vol. 17, No. 3, 1994 in the article *Activity based sleep-wake identification: An empirical test of methodological issues* by A Sadeh, KM Sharkey and MA Carskadon.

For what is worth, I've also tested the actigraph.sleeper implementation to the output of ActiLife 6 [when I had access to the software].

**Comment by dipetkov** [comment]
Link to the original paper: https://academic.oup.com/sleep/article/17/3/201/2749453. It doesn't seem to be behind a paywall.
